name: Test PR
on:
  pull_request:
    branches:
      - '*'
    paths:
      - '**.py'
      - 'example_site/pyproject.toml'
      - 'example_site/poetry.lock'
      - 'example_site/tox.ini'
      - '.github/workflows/test-pr.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Install dependencies
        run: |
          cd example_site
          poetry install

      - name: Run tests
        run: |
          cd example_site
          poetry run python manage.py test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Install dependencies
        run: |
          poetry install

      - name: Run flake8
        run: poetry run flake8

      - name: Run Black
        run: poetry run black --check .
